import numpy as np
import pandas as pd

In [4]:
books=pd.read_csv('Books.csv')
users=pd.read_csv('Users.csv')
ratings=pd.read_csv('Ratings.csv')

In [5]:
#popularity based recommend system

In [6]:
#merging ratings and books data with respect to isbn as it is available in both

In [7]:
ratings_with_name=ratings.merge(books,on='ISBN')

In [8]:
num_rating_df=ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)

In [9]:
num_rating_df

                                              Book-Title  num_ratings
0       Earth Prayers From around the World: 365 Pray...           10
1       Final Fantasy Anthology: Official Strategy Gu...            4
2       Flight of Fancy: American Heiresses (Zebra Ba...            2
3       Little Comic Shop of Horrors (Give Yourself G...            4
4                                           Mystery Mile            2
...                                                  ...          ...
68750                                      Ã?Â?lpiraten.            2
68751                     Ã?Â?rger mit Produkt X. Roman.            4
68752                                Ã?Â?sterlich leben.            1
68753                              Ã?Â?stlich der Berge.            3
68754                                  Ã?Â?thique en toc            2

[68755 rows x 2 columns]

In [10]:
#now taking the avg ratings by using mean operating

In [11]:
avg_rating_df=ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_ratings'},inplace=True)
avg_rating_df

                                              Book-Title  avg_ratings
0       Earth Prayers From around the World: 365 Pray...     5.000000
1       Final Fantasy Anthology: Official Strategy Gu...     5.000000
2       Flight of Fancy: American Heiresses (Zebra Ba...     4.000000
3       Little Comic Shop of Horrors (Give Yourself G...     1.250000
4                                           Mystery Mile     0.000000
...                                                  ...          ...
68750                                      Ã?Â?lpiraten.     0.000000
68751                     Ã?Â?rger mit Produkt X. Roman.     5.250000
68752                                Ã?Â?sterlich leben.     7.000000
68753                              Ã?Â?stlich der Berge.     2.666667
68754                                  Ã?Â?thique en toc     4.000000

[68755 rows x 2 columns]

In [12]:
#now merging num_rating_df and avg_rating_df with respect to Book-Title and assigning it with popularity_df

In [13]:
popularity_df=num_rating_df.merge(avg_rating_df,on='Book-Title')

In [14]:
popularity_df

,Book-Title,num_ratings,avg_ratings
0,Earth Prayers From around the World: 365 Pray...,10,5.000000
1,Final Fantasy Anthology: Official Strategy Gu...,4,5.000000
2,Flight of Fancy: American Heiresses (Zebra Ba...,2,4.000000
3,Little Comic Shop of Horrors (Give Yourself G...,4,1.250000
4,Mystery Mile,2,0.000000
...,...,...,...
68750,Ã?Â?lpiraten.,2,0.000000
68751,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
68752,Ã?Â?sterlich leben.,1,7.000000
68753,Ã?Â?stlich der Berge.,3,2.666667
68754,Ã?Â?thique en toc,2,4.000000

In [15]:
#we will only keep books with num_rating which is number of ratings more than 100

In [16]:
popularity_df=popularity_df[popularity_df['num_ratings']>=100].sort_values('avg_ratings',ascending=False).head(50)

In [17]:
#popularity_df is the top 50 books on this platform

In [18]:
#now getting books author name its image and other details by merging it with books dataset

In [19]:
popularity_df=popularity_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','BookAuthor','Image-URL-M','num_ratings','avg_ratings']]

In [20]:
#collaborative recommendate system

In [21]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 80
regular_users = x[x].index

In [22]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(regular_users)]

In [23]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=10
famous_books = y[y].index

In [24]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [25]:
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [26]:
pt.fillna(0,inplace=True)

In [27]:
pt

User-ID,3363,6251,6575,7346,11601,11676,11993,12538,12824,12835,...,266226,268110,268330,269566,270713,271284,274061,274308,275970,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
16 Lighthouse Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
204 Rosewood Lane,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
311 Pelican Court,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7b,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A 2nd Helping of Chicken Soup for the Soul (Chicken Soup for the Soul Series (Paper)),0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Widow's Walk,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0
Windy City Blues (V.I. Warshawski Novels (Paperback)),0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
With A Southern Touch,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
With Malice,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Year of Wonders: A Novel of the Plague,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
similarity_scores = cosine_similarity(pt)

In [30]:
similarity_scores.shape

(470, 470)

In [31]:
def recommend(book_name):
    #getting index or position of book 
    index=np.where(pt.index==book_name)[0][0]
    similar_books=sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:5]
    
    for i in similar_books:
        print(pt.index[i[0]])

In [34]:
recommend("311 Pelican Court")

204 Rosewood Lane
North Of Clever
The Bad Witness
Like Silk